# Generated by Django 3.1.3 on 2020-12-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user', 'friend')},
        ),
    ]
