# Generated by Django 3.1.3 on 2021-01-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_service', '0004_auto_20210102_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPrivate',
        ),
    ]
