# Generated by Django 3.1.3 on 2021-01-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_service', '0005_delete_chatprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app_service.user')),
            ],
        ),
    ]
