# Generated by Django 3.1.3 on 2021-01-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_service', '0006_chatprivate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPrivate',
        ),
    ]
